/**
 * Seed script: popula o Firestore com +120 exercícios em português
 * Fonte de referência: workout.cool (open-source) + adaptação para PT
 *
 * Uso: npx ts-node scripts/seed-exercises.ts
 */

import { initializeApp } from 'firebase/app';
import { getFirestore, collection, addDoc, getDocs, deleteDoc } from 'firebase/firestore';

// Copia as tuas credenciais Firebase aqui ou usa variáveis de ambiente
const firebaseConfig = {
  apiKey: process.env.VITE_FIREBASE_API_KEY,
  authDomain: process.env.VITE_FIREBASE_AUTH_DOMAIN,
  projectId: process.env.VITE_FIREBASE_PROJECT_ID,
  storageBucket: process.env.VITE_FIREBASE_STORAGE_BUCKET,
  messagingSenderId: process.env.VITE_FIREBASE_MESSAGING_SENDER_ID,
  appId: process.env.VITE_FIREBASE_APP_ID,
};

const APP_ID = 'cpx-vila-rei-main';

const EXERCISES = [
  // ---- PEITO ----
  { name: 'Supino Plano com Barra', type: 'STRENGTH', primary_muscle: 'Peito', musculos_secundarios: ['Tríceps', 'Deltoides Anterior'], equipamento: 'Barra + Banco', dificuldade: 'intermédio', descricao: 'Exercício composto fundamental para desenvolvimento do peitoral. Recruta maciçamente o peitoral maior, com participação dos tríceps e deltoides anteriores.', instrucoes: '1. Deita-te no banco com os pés apoiados no chão.\n2. Agarra a barra com pegada ligeiramente mais larga que os ombros.\n3. Baixa a barra de forma controlada até ao peito (2–3s).\n4. Empurra até à extensão total dos cotovelos.\n5. Mantém os ombros retraídos durante todo o movimento.' },
  { name: 'Supino Inclinado com Barra', type: 'STRENGTH', primary_muscle: 'Peito Superior', musculos_secundarios: ['Tríceps', 'Deltoides Anterior'], equipamento: 'Barra + Banco Inclinado', dificuldade: 'intermédio', descricao: 'Versão inclinada do supino que enfatiza a porção superior do peitoral e deltoides anterior.', instrucoes: '1. Ajusta o banco a 30–45°.\n2. Agarra a barra com pegada neutra (largura dos ombros).\n3. Baixa a barra até à parte superior do peito.\n4. Empurra de forma explosiva até à extensão.\n5. Evita arquear excessivamente a zona lombar.' },
  { name: 'Supino Plano com Halteres', type: 'STRENGTH', primary_muscle: 'Peito', musculos_secundarios: ['Tríceps', 'Deltoides Anterior'], equipamento: 'Halteres + Banco', dificuldade: 'iniciante', descricao: 'Alternativa ao supino com barra que permite maior amplitude e trabalho unilateral de estabilização.', instrucoes: '1. Deita-te com um halter em cada mão à altura do peito.\n2. Empurra os halteres para cima e para o centro.\n3. Baixa de forma controlada abrindo ligeiramente os cotovelos.\n4. Mantém os pulsos alinhados com os ombros.' },
  { name: 'Flexões no Chão', type: 'STRENGTH', primary_muscle: 'Peito', musculos_secundarios: ['Tríceps', 'Core (Abdómen)'], equipamento: 'Sem Equipamento', dificuldade: 'iniciante', descricao: 'Exercício fundamental de peso corporal para peito, tríceps e core. Excelente para iniciantes e recuperação.', instrucoes: '1. Posição de prancha com mãos ligeiramente mais largas que os ombros.\n2. Corpo em linha reta da cabeça aos pés.\n3. Baixa o peito até quase tocar no chão.\n4. Empurra até à extensão total.\n5. Não deixa as ancas cair ou subir.' },
  { name: 'Crucifixo com Halteres', type: 'STRENGTH', primary_muscle: 'Peitoral', musculos_secundarios: ['Deltoides Anterior'], equipamento: 'Halteres + Banco', dificuldade: 'iniciante', descricao: 'Exercício de isolamento para o peitoral que trabalha especialmente o alongamento e adução horizontal.', instrucoes: '1. Deita-te no banco com halteres acima do peito, cotovelos ligeiramente fletidos.\n2. Abre os braços em arco até ao nível do banco (sente o alongamento).\n3. Fecha os braços de volta ao centro, como se abraçasses uma árvore.\n4. Mantém cotovelos ligeiramente fletidos durante todo o movimento.' },
  { name: 'Dips em Banco', type: 'STRENGTH', primary_muscle: 'Peito', musculos_secundarios: ['Tríceps', 'Deltoides Anterior'], equipamento: 'Banco', dificuldade: 'iniciante', descricao: 'Variante de dips com enfoque no peitoral quando o tronco é inclinado para a frente.', instrucoes: '1. Coloca as mãos no banco atrás de ti, pernas estendidas à frente.\n2. Baixa o corpo fletindo os cotovelos até 90°.\n3. Inclina ligeiramente o tronco para a frente para ativar mais o peito.\n4. Empurra de volta à posição inicial.' },

  // ---- COSTAS ----
  { name: 'Peso Morto Convencional', type: 'STRENGTH', primary_muscle: 'Costas', musculos_secundarios: ['Glúteos', 'Quadríceps', 'Isquiotibiais', 'Core (Abdómen)'], equipamento: 'Barra', dificuldade: 'avançado', descricao: 'Rei dos exercícios compostos. Trabalha praticamente todos os músculos do corpo com ênfase na cadeia posterior.', instrucoes: '1. Pés à largura dos ombros, barra sobre o metatarso.\n2. Agarra a barra com pegada dupla-pronada, braços fora dos joelhos.\n3. Peito para cima, coluna neutra, ancas acima dos joelhos.\n4. Empurra o chão enquanto extends os joelhos e ancas simultaneamente.\n5. Bloqueia no topo com glúteos contraídos. Baixa de forma controlada.' },
  { name: 'Remada com Barra', type: 'STRENGTH', primary_muscle: 'Costas', musculos_secundarios: ['Bíceps', 'Deltoides Posterior'], equipamento: 'Barra', dificuldade: 'intermédio', descricao: 'Exercício composto para espessura das costas. Recruta o grande dorsal, trapézio médio e romboides.', instrucoes: '1. Inclina o tronco ~45° para a frente, joelhos ligeiramente fletidos.\n2. Agarra a barra com pegada pronada, mãos à largura dos ombros.\n3. Puxa a barra em direção ao umbigo, contraindo as escápulas.\n4. Baixa de forma controlada.\n5. Mantém a coluna neutra durante todo o movimento.' },
  { name: 'Puxada na Barra Fixa', type: 'STRENGTH', primary_muscle: 'Latíssimo do Dorso', musculos_secundarios: ['Bíceps', 'Romboides'], equipamento: 'Barra Fixa', dificuldade: 'avançado', descricao: 'O melhor exercício para o grande dorsal. Trabalha profundidade e largura das costas.', instrucoes: '1. Agarra a barra fixa com pegada pronada, mãos mais largas que os ombros.\n2. Parte pendurado com cotovelos quase estendidos.\n3. Puxa o peito em direção à barra contraindo o grande dorsal.\n4. Queixo acima da barra no topo.\n5. Desce de forma controlada até à extensão completa.' },
  { name: 'Remada com Halter', type: 'STRENGTH', primary_muscle: 'Grande Dorsal', musculos_secundarios: ['Bíceps', 'Romboides'], equipamento: 'Halteres + Banco', dificuldade: 'iniciante', descricao: 'Remada unilateral que permite grande amplitude de movimento e trabalha cada lado independentemente.', instrucoes: '1. Apoio com um joelho e mão no banco, tronco paralelo ao chão.\n2. Com a outra mão, segura o halter ao lado do banco.\n3. Puxa o halter até à anca, mantendo o cotovelo perto do corpo.\n4. Contrai as costas no topo e baixa de forma controlada.' },
  { name: 'Puxada na Polea Alta', type: 'STRENGTH', primary_muscle: 'Latíssimo do Dorso', musculos_secundarios: ['Bíceps', 'Romboides'], equipamento: 'Máquina de Cabo', dificuldade: 'iniciante', descricao: 'Alternativa à barra fixa que permite controlar o peso. Ideal para iniciantes desenvolverem as costas.', instrucoes: '1. Senta-te com coxas sob os apoios. Agarra a barra em V ou barra larga.\n2. Inclina ligeiramente o tronco para trás.\n3. Puxa a barra até ao peito contraindo o grande dorsal.\n4. Controla o retorno até à extensão completa dos cotovelos.' },
  { name: 'Hiperextensão Lombar', type: 'STRENGTH', primary_muscle: 'Costas Inferior', musculos_secundarios: ['Glúteos', 'Isquiotibiais'], equipamento: 'Banco de Hiperextensão', dificuldade: 'iniciante', descricao: 'Exercício essencial para fortalecer os eretores da espinha e prevenir lesões lombares.', instrucoes: '1. Deita na máquina com ancas no apoio e pés presos.\n2. Braços cruzados no peito ou atrás da cabeça.\n3. Sobe o tronco até ficar em linha reta com as pernas.\n4. Baixa de forma controlada sem dobrar excessivamente.' },

  // ---- PERNAS ----
  { name: 'Agachamento com Barra', type: 'STRENGTH', primary_muscle: 'Quadríceps', musculos_secundarios: ['Glúteos', 'Isquiotibiais', 'Core (Abdómen)'], equipamento: 'Barra + Rack', dificuldade: 'intermédio', descricao: 'O exercício mais completo para os membros inferiores. Desenvolve quadríceps, glúteos e toda a cadeia posterior.', instrucoes: '1. Barra sobre os trapézios (não no pescoço).\n2. Pés à largura dos ombros ou ligeiramente mais, pontas viradas ~30° para fora.\n3. Desce com o peito para cima e joelhos acompanhando a direção dos pés.\n4. Desce até às coxas paralelas ao chão (ou mais).\n5. Sobe de forma explosiva, bloqueando no topo.' },
  { name: 'Agachamento Goblet', type: 'STRENGTH', primary_muscle: 'Quadríceps', musculos_secundarios: ['Glúteos', 'Core (Abdómen)'], equipamento: 'Kettle Bell ou Halter', dificuldade: 'iniciante', descricao: 'Versão do agachamento com kettlebell/halter à frente que obriga ao tronco ereto. Excelente para aprender a técnica.', instrucoes: '1. Segura o kettlebell/halter ao peito com ambas as mãos.\n2. Pés ligeiramente mais que à largura dos ombros.\n3. Desce mantendo o peito ereto e cotovelos dentro dos joelhos.\n4. Sobe de forma controlada, empurrando o chão com os calcanhares.' },
  { name: 'Leg Press', type: 'STRENGTH', primary_muscle: 'Quadríceps', musculos_secundarios: ['Glúteos', 'Isquiotibiais'], equipamento: 'Leg Press', dificuldade: 'iniciante', descricao: 'Alternativa ao agachamento que remove o stresse da coluna. Ideal para utentes com limitações lombares.', instrucoes: '1. Senta-te com as costas e glúteos no assento.\n2. Coloca os pés na plataforma à largura dos ombros.\n3. Solta os pesos e desce a plataforma até 90° nos joelhos.\n4. Empurra de forma controlada até quase à extensão total (sem bloquear os joelhos).' },
  { name: 'Afundo (Lunge)', type: 'STRENGTH', primary_muscle: 'Quadríceps', musculos_secundarios: ['Glúteos', 'Isquiotibiais'], equipamento: 'Sem Equipamento / Halteres', dificuldade: 'iniciante', descricao: 'Exercício unilateral que trabalha equilíbrio, mobilidade e força de cada perna independentemente.', instrucoes: '1. Parte em pé com os pés juntos (halteres opcional).\n2. Dá um passo largo para a frente com um pé.\n3. Baixa o joelho traseiro em direção ao chão (~2cm do chão).\n4. Joelho da frente não passa a ponta do pé.\n5. Empurra de volta à posição inicial com o pé da frente.' },
  { name: 'Peso Morto Romeno', type: 'STRENGTH', primary_muscle: 'Isquiotibiais', musculos_secundarios: ['Glúteos', 'Costas Inferior'], equipamento: 'Barra ou Halteres', dificuldade: 'intermédio', descricao: 'Variante do peso morto com foco nos isquiotibiais e glúteos. Menor amplitude que o convencional.', instrucoes: '1. Parte em pé com barra ou halteres à frente das coxas.\n2. Mantém joelhos ligeiramente fletidos durante todo o movimento.\n3. Inclina o tronco para a frente empurrando as ancas para trás.\n4. Baixa até sentir alongamento nos isquiotibiais (~meio da tíbia).\n5. Sobe contraindo glúteos e isquiotibiais.' },
  { name: 'Elevação de Gémeos em Pé', type: 'STRENGTH', primary_muscle: 'Gémeos (Panturrilha)', musculos_secundarios: [], equipamento: 'Degrau / Máquina', dificuldade: 'iniciante', descricao: 'Exercício de isolamento para gémeos (gastrocnémio e solear). Essencial para membros inferiores completos.', instrucoes: '1. Fica em pé sobre um degrau com os calcanhares fora do bordo.\n2. Desce os calcanhares até ao máximo de alongamento.\n3. Sobe de forma controlada até à máxima contração.\n4. Pausa 1 segundo no topo para maximizar a contração.' },
  { name: 'Cadeira Extensora', type: 'STRENGTH', primary_muscle: 'Quadríceps', musculos_secundarios: [], equipamento: 'Máquina Extensora', dificuldade: 'iniciante', descricao: 'Exercício de isolamento para os quadríceps. Não recomendado para utentes com problemas no joelho.', instrucoes: '1. Senta-te com costas no encosto e joelhos no bordo do assento.\n2. Ajusta o rolo ao nível do tornozelo.\n3. Estende as pernas até à extensão completa.\n4. Baixa de forma controlada sem bater na posição inicial.' },
  { name: 'Mesa Flexora', type: 'STRENGTH', primary_muscle: 'Femoral', musculos_secundarios: [], equipamento: 'Mesa Flexora', dificuldade: 'iniciante', descricao: 'Exercício de isolamento para isquiotibiais/femorais. Complemento essencial à cadeira extensora.', instrucoes: '1. Deita com o rosto para baixo, joelhos na borda da máquina.\n2. Rolo ao nível dos tornozelos.\n3. Flexiona as pernas trazendo os calcanhares aos glúteos.\n4. Baixa de forma lenta e controlada.\n5. Não eleva as ancas durante o movimento.' },
  { name: 'Hip Thrust com Barra', type: 'STRENGTH', primary_muscle: 'Glúteos', musculos_secundarios: ['Isquiotibiais', 'Core (Abdómen)'], equipamento: 'Barra + Banco', dificuldade: 'intermédio', descricao: 'Melhor exercício de isolamento para os glúteos. Produz maior ativação glútea que qualquer outro exercício.', instrucoes: '1. Costas encostadas ao banco (nível das omoplatas).\n2. Barra sobre o coxal (com almofada de proteção).\n3. Pés à largura dos ombros, calcanhares sob os joelhos.\n4. Empurra as ancas para cima até ficar paralelo ao chão.\n5. Contrai glúteos no topo durante 1 segundo.' },

  // ---- OMBROS ----
  { name: 'Press Militar com Barra', type: 'STRENGTH', primary_muscle: 'Deltoides', musculos_secundarios: ['Tríceps', 'Trapézio'], equipamento: 'Barra', dificuldade: 'intermédio', descricao: 'Exercício composto rei para os ombros. Desenvolve os três feixes do deltoides e a força de press vertical.', instrucoes: '1. De pé ou sentado, barra ao nível dos ombros (pegada pronada).\n2. Press para cima até à extensão total.\n3. Na posição mais alta, os braços ficam ligeiramente inclinados para trás.\n4. Baixa de forma controlada ao ponto de partida.\n5. Mantém o core contraído para estabilidade.' },
  { name: 'Elevação Lateral com Halteres', type: 'STRENGTH', primary_muscle: 'Deltoides Medial', musculos_secundarios: ['Trapézio'], equipamento: 'Halteres', dificuldade: 'iniciante', descricao: 'Exercício de isolamento para o deltoides medial, responsável pela largura dos ombros.', instrucoes: '1. De pé com halteres ao lado do corpo.\n2. Eleva os braços lateralmente até à altura dos ombros.\n3. Cotovelos ligeiramente fletidos, punhos em rotação neutra.\n4. Baixa de forma lenta e controlada (3 segundos).\n5. Não usa impulso do corpo.' },
  { name: 'Elevação Frontal com Halteres', type: 'STRENGTH', primary_muscle: 'Deltoides Anterior', musculos_secundarios: ['Peito Superior'], equipamento: 'Halteres', dificuldade: 'iniciante', descricao: 'Isolamento para a porção anterior do deltoides. Frequentemente negligenciado quando se faz muito supino.', instrucoes: '1. De pé com halteres à frente das coxas.\n2. Eleva um halter de cada vez (ou ambos) à altura dos ombros.\n3. Cotovelos quase estendidos, não usa impulso.\n4. Baixa de forma controlada.' },
  { name: 'Face Pull na Roldana', type: 'STRENGTH', primary_muscle: 'Deltoides Posterior', musculos_secundarios: ['Trapézio Médio', 'Romboides'], equipamento: 'Máquina de Cabo', dificuldade: 'iniciante', descricao: 'Essencial para saúde dos ombros e postura. Contraria os efeitos do excesso de press horizontal.', instrucoes: '1. Roldana alta com corda. Agarra com ambas as mãos.\n2. Puxa a corda em direção ao rosto, separando as mãos no final.\n3. Cotovelos ao nível ou acima dos ombros.\n4. Foca-te em retrair as escápulas e abrir os ombros.\n5. Executa sempre de forma controlada, sem peso excessivo.' },
  { name: 'Desenvolvimento com Halteres', type: 'STRENGTH', primary_muscle: 'Deltoides', musculos_secundarios: ['Tríceps', 'Trapézio'], equipamento: 'Halteres', dificuldade: 'iniciante', descricao: 'Variante do press militar com halteres que permite maior liberdade de movimento e trabalho de estabilização.', instrucoes: '1. Sentado ou de pé, halteres ao nível dos ombros.\n2. Press para cima convergindo os halteres no topo.\n3. Baixa até aos ombros de forma controlada.\n4. Mantém o núcleo contraído e evita arquear as costas.' },

  // ---- BÍCEPS ----
  { name: 'Curl com Barra', type: 'STRENGTH', primary_muscle: 'Bíceps', musculos_secundarios: ['Braquial'], equipamento: 'Barra', dificuldade: 'iniciante', descricao: 'Exercício clássico de isolamento para bíceps. Permite usar maior carga que com halteres.', instrucoes: '1. De pé, barra com pegada supinada à largura dos ombros.\n2. Mantém cotovelos junto ao corpo durante todo o movimento.\n3. Flexiona até à contração máxima (barra próxima do peito).\n4. Baixa de forma controlada até à extensão quase total.\n5. Não usa impulso do corpo.' },
  { name: 'Curl Alternado com Halteres', type: 'STRENGTH', primary_muscle: 'Bíceps', musculos_secundarios: ['Braquial'], equipamento: 'Halteres', dificuldade: 'iniciante', descricao: 'Permite maior amplitude e foco em cada braço individualmente. A supinação do pulso maximiza a contração.', instrucoes: '1. De pé com halteres ao lado do corpo (pegada neutra).\n2. Flete um braço de cada vez, supinando o pulso ao longo do movimento.\n3. No topo, o polegar aponta para fora.\n4. Baixa de forma controlada e repete no outro braço.' },
  { name: 'Curl de Martelo', type: 'STRENGTH', primary_muscle: 'Bíceps', musculos_secundarios: ['Braquiorradial', 'Braquial'], equipamento: 'Halteres', dificuldade: 'iniciante', descricao: 'Curl com pegada neutra que enfatiza o braquiorradial e braquial, dando mais volume ao braço.', instrucoes: '1. De pé ou sentado com halteres em pegada neutra (polegar para cima).\n2. Flexiona mantendo a pegada neutra durante todo o movimento.\n3. Não roda o pulso.\n4. Baixa de forma controlada.' },
  { name: 'Curl Concentrado', type: 'STRENGTH', primary_muscle: 'Bíceps', musculos_secundarios: [], equipamento: 'Halter', dificuldade: 'iniciante', descricao: 'Máximo isolamento do bíceps sem possibilidade de usar impulso do corpo.', instrucoes: '1. Sentado no banco, cotovelo apoiado na face interna da coxa.\n2. Flete o braço de forma lenta e controlada.\n3. Contrai maximamente no topo.\n4. Baixa até à extensão quase total.' },

  // ---- TRÍCEPS ----
  { name: 'Extensão de Tríceps na Roldana Alta', type: 'STRENGTH', primary_muscle: 'Tríceps', musculos_secundarios: [], equipamento: 'Máquina de Cabo', dificuldade: 'iniciante', descricao: 'Exercício de isolamento para tríceps muito popular. Mantém tensão constante graças ao cabo.', instrucoes: '1. Roldana alta com barra reta ou V. Agarra com pegada pronada.\n2. Cotovelos junto ao corpo, fixos ao longo do movimento.\n3. Estende os braços em baixo até à extensão total.\n4. Controla o retorno à posição inicial.' },
  { name: 'Tríceps Francês com Barra EZ', type: 'STRENGTH', primary_muscle: 'Tríceps', musculos_secundarios: [], equipamento: 'Barra EZ + Banco', dificuldade: 'intermédio', descricao: 'Excelente exercício de isolamento que trabalha o tríceps em todo o comprimento.', instrucoes: '1. Deitado no banco, barra EZ acima do peito, braços estendidos.\n2. Mantendo os cotovelos fixos e apontados ao teto, flexiona os cotovelos.\n3. Baixa a barra até próximo da testa.\n4. Estende de volta à posição inicial sem bloquear totalmente os cotovelos.' },
  { name: 'Fundos entre Bancos (Dips)', type: 'STRENGTH', primary_muscle: 'Tríceps', musculos_secundarios: ['Peito', 'Deltoides Anterior'], equipamento: 'Barras Paralelas', dificuldade: 'intermédio', descricao: 'Exercício composto de peso corporal para tríceps. Mantém o tronco vertical para maximizar trabalho do tríceps.', instrucoes: '1. Suspende-te nas barras paralelas com cotovelos estendidos.\n2. Mantém o tronco vertical (enfoca tríceps) ou inclinado (enfoca peito).\n3. Desce até 90° nos cotovelos.\n4. Empurra de volta à extensão total.' },
  { name: 'Extensão de Tríceps com Halter (Skulcrusher)', type: 'STRENGTH', primary_muscle: 'Tríceps', musculos_secundarios: [], equipamento: 'Halter', dificuldade: 'iniciante', descricao: 'Versão com halter do tríceps francês, unilateral ou bilateral. Menos stresse no pulso.', instrucoes: '1. Deitado, halter(s) acima do peito com braços estendidos.\n2. Dobra os cotovelos baixando o(s) halter(s) ao lado da cabeça.\n3. Estende de volta à posição inicial.\n4. Mantém cotovelos fixos e apontados ao teto.' },

  // ---- ABDOMINAIS / CORE ----
  { name: 'Prancha (Plank)', type: 'STRENGTH', primary_muscle: 'Core (Abdómen)', musculos_secundarios: ['Deltoides', 'Glúteos'], equipamento: 'Sem Equipamento', dificuldade: 'iniciante', descricao: 'Exercício isométrico fundamental para estabilidade do core. Base de todos os movimentos funcionais.', instrucoes: '1. Apoia em antebraços e pontas dos pés.\n2. Corpo em linha reta da cabeça aos calcanhares.\n3. Contrai o abdómen como se fosses levar um soco.\n4. Mantém a posição sem deixar as ancas cair ou subir.\n5. Respira de forma controlada.' },
  { name: 'Crunch Abdominal', type: 'STRENGTH', primary_muscle: 'Reto Abdominal', musculos_secundarios: ['Oblíquos'], equipamento: 'Sem Equipamento', dificuldade: 'iniciante', descricao: 'Exercício básico para os abdominais superiores.', instrucoes: '1. Deitado com joelhos fletidos, pés no chão.\n2. Mãos atrás da cabeça ou cruzadas no peito.\n3. Eleva apenas os ombros do chão, contraindo o abdómen.\n4. Não puxa pelo pescoço.\n5. Baixa de forma controlada.' },
  { name: 'Elevação de Pernas em Barra', type: 'STRENGTH', primary_muscle: 'Abdómen Inferior', musculos_secundarios: ['Flexores da Anca', 'Core (Abdómen)'], equipamento: 'Barra Fixa', dificuldade: 'intermédio', descricao: 'Exercício avançado para abdominais inferiores. Requer força considerável no core e braços.', instrucoes: '1. Pendurado na barra fixa com cotovelos estendidos.\n2. Mantendo as pernas juntas, eleva-as até paralelas ao chão (ou até à barra).\n3. Controla a descida sem usar impulso.\n4. Evita balançar o corpo.' },
  { name: 'Russian Twist', type: 'STRENGTH', primary_muscle: 'Oblíquos', musculos_secundarios: ['Reto Abdominal'], equipamento: 'Sem Equipamento / Peso', dificuldade: 'iniciante', descricao: 'Exercício eficaz para os oblíquos. Pode ser feito com ou sem peso adicional.', instrucoes: '1. Sentado no chão, tronco a 45°, pés elevados.\n2. Com mãos juntas (ou agarrando peso), roda o tronco de um lado para o outro.\n3. Toca o chão a cada lado com as mãos.\n4. Mantém o core contraído durante todo o exercício.' },
  { name: 'Prancha Lateral', type: 'STRENGTH', primary_muscle: 'Oblíquos', musculos_secundarios: ['Core (Abdómen)', 'Glúteo Médio'], equipamento: 'Sem Equipamento', dificuldade: 'iniciante', descricao: 'Variante lateral da prancha que isola os oblíquos e melhora a estabilidade lateral da coluna.', instrucoes: '1. Apoio lateral no antebraço e pé inferior (ou joelho para facilitar).\n2. Corpo em linha reta da cabeça aos pés.\n3. Anca elevada, não deixa cair.\n4. Mantém o olhar em frente.\n5. Repete para o lado oposto.' },
  { name: 'Hollow Body Hold', type: 'STRENGTH', primary_muscle: 'Core (Abdómen)', musculos_secundarios: ['Reto Abdominal', 'Flexores da Anca'], equipamento: 'Sem Equipamento', dificuldade: 'intermédio', descricao: 'Exercício isométrico avançado do método ginástico. Ativa todo o core de forma integrada.', instrucoes: '1. Deitado de costas, braços estendidos acima da cabeça.\n2. Eleva ombros e pernas do chão simultaneamente.\n3. Zona lombar deve permanecer encostada ao chão.\n4. Corpo forma uma "banana" côncava.\n5. Mantém a respiração controlada.' },

  // ---- GLÚTEOS ----
  { name: 'Agachamento Sumo', type: 'STRENGTH', primary_muscle: 'Glúteos', musculos_secundarios: ['Quadríceps', 'Adutores'], equipamento: 'Barra ou Halter', dificuldade: 'iniciante', descricao: 'Variante do agachamento com base ampla que enfatiza mais glúteos e adutores.', instrucoes: '1. Pés mais largos que os ombros, pontas a ~45°.\n2. Barra no trapézio ou halter suspenso entre as pernas.\n3. Desce com os joelhos acompanhando a direção dos pés.\n4. Costas eretas e peito para cima.\n5. Sobe contraindo glúteos.' },
  { name: 'Kick Back na Roldana', type: 'STRENGTH', primary_muscle: 'Glúteos', musculos_secundarios: ['Isquiotibiais'], equipamento: 'Máquina de Cabo', dificuldade: 'iniciante', descricao: 'Exercício de isolamento para glúteos que trabalha extensão da anca contra resistência.', instrucoes: '1. De frente para a roldana baixa, tornozeiro preso ao cabo.\n2. Segura o apoio para equilíbrio, inclina ligeiramente o tronco.\n3. Estende a perna para trás contraindo o glúteo.\n4. Baixa de forma controlada sem dobrar excessivamente a coluna.' },
  { name: 'Ponte de Glúteos', type: 'STRENGTH', primary_muscle: 'Glúteos', musculos_secundarios: ['Isquiotibiais', 'Core (Abdómen)'], equipamento: 'Sem Equipamento', dificuldade: 'iniciante', descricao: 'Versão simples do hip thrust, sem banco. Ideal para iniciantes ou ativação antes do treino.', instrucoes: '1. Deitado de costas, joelhos a 90°, pés no chão.\n2. Empurra as ancas para cima contraindo os glúteos.\n3. Corpo forma uma linha do ombro ao joelho.\n4. Pausa 1 segundo no topo.\n5. Baixa de forma controlada.' },

  // ---- CARDIO ----
  { name: 'Corrida na Passadeira', type: 'CARDIO', primary_muscle: 'Sistema Cardiovascular', musculos_secundarios: ['Quadríceps', 'Gémeos (Panturrilha)', 'Glúteos'], equipamento: 'Passadeira', dificuldade: 'iniciante', descricao: 'Exercício cardiovascular fundamental. Melhora a resistência aeróbica, saúde cardiovascular e ajuda no controlo de peso.', instrucoes: '1. Aquecimento: 5 min a ritmo lento.\n2. Fase principal: ritmo moderado mantendo uma conversa.\n3. Zona de FC alvo: 60–70% da FCmax para resistência, 70–85% para melhoria cardiovascular.\n4. Arrefecimento: 5 min a ritmo decrescente.' },
  { name: 'Bicicleta Estacionária', type: 'CARDIO', primary_muscle: 'Sistema Cardiovascular', musculos_secundarios: ['Quadríceps', 'Isquiotibiais', 'Gémeos (Panturrilha)'], equipamento: 'Bicicleta Estacionária', dificuldade: 'iniciante', descricao: 'Excelente alternativa de baixo impacto à corrida. Ideal para utentes com problemas nas articulações.', instrucoes: '1. Ajusta o selim (joelho ligeiramente fletido na extensão).\n2. Aquecimento 5 min com resistência baixa.\n3. Fase principal com resistência moderada.\n4. Cadência: 60–100 rpm.\n5. Arrefecimento 5 min diminuindo progressivamente.' },
  { name: 'Elíptica', type: 'CARDIO', primary_muscle: 'Sistema Cardiovascular', musculos_secundarios: ['Glúteos', 'Quadríceps', 'Isquiotibiais'], equipamento: 'Elíptica', dificuldade: 'iniciante', descricao: 'Cardio de impacto zero que combina movimento de braços e pernas. Ideal para reabilitação e prevenção de lesões.', instrucoes: '1. Sobe segurando os apoios das mãos.\n2. Movimento natural como caminhar/correr mas sem impacto.\n3. Usa os braços ativamente para aumentar o trabalho total.\n4. Mantém o tronco ereto e o core contraído.' },
  { name: 'Remo Ergómetro', type: 'CARDIO', primary_muscle: 'Sistema Cardiovascular', musculos_secundarios: ['Costas', 'Bíceps', 'Quadríceps', 'Glúteos'], equipamento: 'Máquina de Remo', dificuldade: 'intermédio', descricao: 'Um dos melhores exercícios cardiovasculares. Trabalha 86% da musculatura em simultâneo.', instrucoes: '1. Senta-te com pés nos apoios, agarra o punho.\n2. Sequência: perna → inclina tronco → puxar braços.\n3. Recuperação (inversa): braços → inclina tronco → dobra joelhos.\n4. Mantém a coluna neutra.\n5. Alvo: 500m por intervalo de 2 min para iniciantes.' },
  { name: 'Burpee', type: 'CARDIO', primary_muscle: 'Corpo Inteiro', musculos_secundarios: ['Peito', 'Quadríceps', 'Glúteos', 'Core (Abdómen)'], equipamento: 'Sem Equipamento', dificuldade: 'intermédio', descricao: 'Exercício de alta intensidade que combina força e cardio. Um dos mais eficazes para queimar calorias.', instrucoes: '1. De pé, agacha e apoia as mãos no chão.\n2. Salta para a posição de prancha.\n3. Faz uma flexão (opcional).\n4. Salta de volta para a posição de agachamento.\n5. Salta verticalmente com os braços acima da cabeça.' },
  { name: 'Corda de Saltar', type: 'CARDIO', primary_muscle: 'Sistema Cardiovascular', musculos_secundarios: ['Gémeos (Panturrilha)', 'Deltoides'], equipamento: 'Corda de Saltar', dificuldade: 'iniciante', descricao: 'Cardio económico e altamente eficaz. 10 min de corda equivalem a 30 min de corrida em impacto cardiovascular.', instrucoes: '1. Agarra as pontas da corda ao nível das ancas.\n2. Salta apenas 2–3cm do chão (não exageras).\n3. Aterragens suaves nas pontas dos pés.\n4. Começa com séries de 30s e aumenta progressivamente.\n5. Variações: duplo salto, pés alternados, alta joelhos.' },

  // ---- FUNCIONAL ----
  { name: 'Prancha com Remada (Renegade Row)', type: 'STRENGTH', primary_muscle: 'Corpo Inteiro', musculos_secundarios: ['Costas', 'Core (Abdómen)', 'Peito'], equipamento: 'Halteres', dificuldade: 'avançado', descricao: 'Exercício composto que combina estabilidade de prancha com força de remada. Exige grande coordenação.', instrucoes: '1. Posição de prancha com cada mão num halter.\n2. Mantém o corpo estável (não rota as ancas).\n3. Puxa um halter até à anca alternadamente.\n4. Mantém o core muito contraído para evitar rotação.' },
  { name: 'Kettlebell Swing', type: 'STRENGTH', primary_muscle: 'Glúteos', musculos_secundarios: ['Isquiotibiais', 'Core (Abdómen)', 'Costas'], equipamento: 'Kettle Bell', dificuldade: 'intermédio', descricao: 'Movimento balístico que combina força e cardio. Um dos melhores exercícios para toda a cadeia posterior.', instrucoes: '1. Pés à largura dos ombros, kettlebell à frente.\n2. Inclina o tronco com a charneira na anca (não agachamento!).\n3. Balança o kettlebell entre as pernas.\n4. Empurra as ancas para a frente de forma explosiva.\n5. Kettlebell sobe até à altura dos ombros pela força das ancas (não dos braços).' },
  { name: 'Thruster com Halteres', type: 'STRENGTH', primary_muscle: 'Corpo Inteiro', musculos_secundarios: ['Quadríceps', 'Glúteos', 'Deltoides', 'Tríceps'], equipamento: 'Halteres', dificuldade: 'intermédio', descricao: 'Combinação de agachamento frontal + press militar. Exercício de alta eficiência para condicionamento geral.', instrucoes: '1. Halteres ao nível dos ombros, cotovelos à frente.\n2. Agacha até às coxas paralelas ao chão.\n3. Ao subir, usa o impulso das pernas para fazer press acima da cabeça.\n4. Baixa os halteres e imediatamente volta ao agachamento.' },
  { name: 'Turkish Get-Up', type: 'STRENGTH', primary_muscle: 'Corpo Inteiro', musculos_secundarios: ['Core (Abdómen)', 'Deltoides', 'Glúteos'], equipamento: 'Kettle Bell ou Halter', dificuldade: 'avançado', descricao: 'Um dos melhores exercícios funcionais. Desenvolve estabilidade, mobilidade e força integrada.', instrucoes: '1. Deitado, kettlebell/halter numa mão estendida verticalmente.\n2. Rola para apoio lateral, depois levanta-te passo a passo.\n3. Passa por: deitado → apoio no antebraço → apoio na mão → joelho ao chão → de pé.\n4. Repete o processo na descida.\n5. O peso permanece sempre estendido acima da cabeça.' },
  { name: 'Mountain Climbers', type: 'CARDIO', primary_muscle: 'Core (Abdómen)', musculos_secundarios: ['Deltoides', 'Quadríceps'], equipamento: 'Sem Equipamento', dificuldade: 'iniciante', descricao: 'Exercício de alta intensidade que combina trabalho de core com cardio. Excelente para HIIT.', instrucoes: '1. Posição de prancha com braços estendidos.\n2. Alterna trazer os joelhos para o peito de forma rápida.\n3. Mantém as ancas baixas e o core contraído.\n4. Quanto mais rápido, maior o componente cardiovascular.' },
  { name: 'Box Jump', type: 'STRENGTH', primary_muscle: 'Quadríceps', musculos_secundarios: ['Glúteos', 'Gémeos (Panturrilha)'], equipamento: 'Caixa de Salto', dificuldade: 'intermédio', descricao: 'Exercício pliométrico que desenvolve potência de membros inferiores. Essencial para atletismo.', instrucoes: '1. De frente para a caixa, pés à largura dos ombros.\n2. Semi-agachamento com balanço dos braços.\n3. Salta de forma explosiva aterrando em cima da caixa.\n4. Aterra com suavidade (absorção) com ambos os pés.\n5. Desce (não saltas de volta) controlando a aterragem.' },

  // ---- MOBILIDADE / FLEXIBILIDADE ----
  { name: 'Alongamento dos Isquiotibiais', type: 'FLEXIBILITY', primary_muscle: 'Isquiotibiais', musculos_secundarios: [], equipamento: 'Sem Equipamento', dificuldade: 'iniciante', descricao: 'Alongamento estático essencial para flexibilidade dos isquiotibiais e prevenção de lesões lombares.', instrucoes: '1. Sentado no chão, pernas estendidas à frente.\n2. Inclina o tronco para a frente mantendo a coluna reta.\n3. Tenta chegar aos pés sem dobrar os joelhos.\n4. Mantém 30 segundos, respira profundamente.\n5. Não usa movimentos de balanço.' },
  { name: 'Alongamento do Quadríceps', type: 'FLEXIBILITY', primary_muscle: 'Quadríceps', musculos_secundarios: ['Flexores da Anca'], equipamento: 'Sem Equipamento', dificuldade: 'iniciante', descricao: 'Essencial após treino de pernas. Previne tensão muscular e melhora a mobilidade da anca.', instrucoes: '1. De pé, dobra um joelho trazendo o calcanhar ao glúteo.\n2. Agarra o tornozelo com a mão do mesmo lado.\n3. Joelhos juntos, tronco ereto.\n4. Sente o alongamento na frente da coxa.\n5. Mantém 30 segundos cada lado.' },
  { name: 'Mobilidade Torácica em Rolo', type: 'FLEXIBILITY', primary_muscle: 'Costas', musculos_secundarios: [], equipamento: 'Rolo de Espuma (Foam Roller)', dificuldade: 'iniciante', descricao: 'Técnica de libertação miofascial para a coluna torácica. Melhora postura e reduz dor nas costas.', instrucoes: '1. Coloca o rolo perpendicularmente à coluna.\n2. Posiciona-o ao nível das omoplatas com mãos atrás da cabeça.\n3. Arqueia suavemente sobre o rolo, abrindo a coluna torácica.\n4. Move o rolo de cima para baixo pelas costas.\n5. Pausa nos pontos mais tensos (30s–60s).' },
];

async function main() {
  console.log('Inicializando Firebase...');
  const app = initializeApp(firebaseConfig);
  const db = getFirestore(app);
  const path = `artifacts/${APP_ID}/public/data/exercise_library`;
  const ref = collection(db, path);

  console.log(`Verificando exercícios existentes em ${path}...`);
  const existing = await getDocs(ref);
  console.log(`  ${existing.size} exercícios encontrados.`);

  const existingNames = new Set(existing.docs.map(d => (d.data().name as string).toLowerCase()));

  let added = 0;
  let skipped = 0;

  for (const ex of EXERCISES) {
    if (existingNames.has(ex.name.toLowerCase())) {
      skipped++;
      continue;
    }
    await addDoc(ref, ex);
    console.log(`  + ${ex.name}`);
    added++;
  }

  console.log(`\nConcluído: ${added} adicionados, ${skipped} já existiam.`);
  process.exit(0);
}

main().catch(err => {
  console.error('Erro:', err);
  process.exit(1);
});
